### ISSUE TITLE
Piackutatás

### ISSUE THREAD

**Issue by szaffo** [szaffo/diakkedvezmeny#111]
# Az mi?

Hirtelen jött az ötlet, hogy kellene egy google űrlapot szétszorni a neten, amiben a diákok kedvezményes pénzöltési kúltúrájáról érdeklődünk. 

### Pro
* Megtudjuk, hogy egyáltalán van-e értelme ennek, amit csinálunk.
* Megtudjuk, hogy mire van szüksége az A célcsoportnak., ezáltal lesz egy képünk arról, hogy milyen feature-ököt kell még implementálni.
* Már megjelenés előtt hallatjuk a nevünket, így nem lesz idegen mikor publikálunk.
* *Fake it till you make it* hozzáálás erősítése. Úgy csináljuk, mint a komolyak, nagyok. Profik látszatát keltjük, így adunk egy alapot az ODA brand-nek.

> Az **A** célcsoport a diákok. A kedvezményt nyújtó helyek a **B**

### Kontra

* Az effort
* Talán rájövünk, hogy felesleges az oldal -> Rethink és megmutatjuk, hogy nem.  *2007 előtt sem gondolták volna az emberek, hogy okostelefonra van szükségük.*

## Megvalósítás

Google űrlap, igényesen megcsinálva

## Időpőpontok

Erről tovább egyeztetünk a csütörtöki meeting-en: **2019.11.21 13:30 - 16:00 @Infópark**

**Comment by szaffo** [comment]
# Meeting

Maximum 10 kérdés, fiatlaos formában. Elején rövid leírás.

## Részek
* Demográfiai: életkor: *gimis, egyetem, egyéb*
* *"szokásokról"*
* Kedvezményekre való fogékonyság 
* az oldalról

## Kérdések

* Nemed
   - Férfi
   - Nő
* Korosztály 
   - Gimis
   - Hallgató
   - Egyéb
* Milyen gyakran jársz el szórakozni?
* Van-e olyan törzshelyed, ahol gyakran megfordulsz?
* Szeretsz felfedezni új helyeket?
* Mennyire figyeled a kedvezményeket amikor mész valahova?
* Befolyásol-e a választásban, ha kedvezményt kínál egy hely?
* Választanál egy helyet azért, mert kedvezményt nyújt?
* Milyen helyeken szeretnél kedvezményt? **?**
    - Étterem
   - Kávézó
   - Mozi
   - Kultúrális helyek
   - Rendezvények
   - Webshop
   - Ruházat
   - Egyéb
* Hasznosnak találnál-e egy olyan oldalt ami összegyűjti a diákkedvezményeket?

## Hozzávalók
Kell az ODA sample kép

**Comment by havrillap** [comment]
https://forms.gle/gkMxRtUAfiTvQGT18
