### ISSUE TITLE
Papers automatizálás

### ISSUE THREAD

**Issue by szaffo** [szaffo/diakkedvezmeny#84]
Kellene egy olyan script ami lefuttatásakor a /papers mappában lévő `.md` fájlokat átalakítja `html` fájlokká, ellátva azokat az ODA website head-jével és footer-jével. Plusz lenne, hogy akár a footer-ben hozzá is adhat egy linket az új html oldalhoz. 

Ezzel gyorsabban lehetne szöveges oldalakat írni markdown-ban, és egységes oldalak lehetnének a szabályzatnak és egyéb információs oldalnak.

**Comment by havrillap** [comment]
Tesztelés alatt

**Comment by havrillap** [comment]
#96 tesztelve, működik
